export const FETCH_DATA_REQUEST_SENT = 'FETCH_DATA_REQUEST_SENT'
export const FETCH_DATA_REQUEST_FAILED = 'FETCH_DATA_REQUEST_FAILED'
export const FETCH_DATA_REQUEST_SUCCEEDED = 'FETCH_DATA_REQUEST_SUCCEEDED'
